### ISSUE TITLE
Getting IllegalStateException on any kotlin file

### ISSUE THREAD

**Issue by DavidArutiunian** [Angry-Potato/prettier-plugin-kotlin#4]
Hi!

I'm trying to get this plugin working, but facing this issue

```
[error] src\main\kotlin\com\backend\Application.kt: Error: Exception in thread "main" java.lang.IllegalStateException: LOGGING: Loading modules: [java.se, jdk.accessibility, jdk.attach, jdk.compiler, jdk.dynal
ink, jdk.httpserver, jdk.jartool, jdk.javadoc, jdk.jconsole, jdk.jdi, jdk.jfr, jdk.jshell, jdk.jsobject, jdk.management, jdk.management.jfr, jdk.net, jdk.scripting.nashorn, jdk.sctp, jdk.security.auth, jdk.security.jgss, jdk.unsuppo
rted, jdk.unsupported.desktop, jdk.xml.dom, java.base, java.compiler, java.datatransfer, java.desktop, java.xml, java.instrument, java.logging, java.management, java.management.rmi, java.rmi, java.naming, java.net.http, java.prefs,
java.scripting, java.security.jgss, java.security.sasl, java.sql, java.transaction.xa, java.sql.rowset, java.xml.crypto, jdk.internal.jvmstat, jdk.management.agent, jdk.jdwp.agent, jdk.internal.ed, jdk.internal.le, jdk.internal.opt]
[error] sageCollector configured)
[error]         at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.report(ClasspathRootsResolver.kt:312)
[error]         at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.report$default(ClasspathRootsResolver.kt:310)
[error]         at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.addModularRoots(ClasspathRootsResolver.kt:253)
[error]         at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.computeRoots(ClasspathRootsResolver.kt:123)
[error]         at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:79)
[error]         at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:228)
[error]         at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:124)
[error]         at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:426)
[error]         at com.github.angrypotato.kotato.Parser$proj$2.invoke(Parser.kt:16)
[error]         at com.github.angrypotato.kotato.Parser$proj$2.invoke(Parser.kt:14)
[error]         at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
[error]         at com.github.angrypotato.kotato.Parser.getProj(Parser.kt)
[error]         at com.github.angrypotato.kotato.Parser.parsePsiFile(Parser.kt:30)
[error]         at com.github.angrypotato.kotato.Parser.parseFile(Parser.kt:23)
[error]         at com.github.angrypotato.kotato.Parser.parseFile$default(Parser.kt:23)
[error]         at com.github.angrypotato.kotato.Parse.run(main.kt:45)
[error]         at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:136)
[error]         at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
[error]         at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:216)
[error]         at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:213)
[error]         at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:231)
[error]         at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:250)
[error]         at com.github.angrypotato.kotato.MainKt.main(main.kt:70)
[error]
[error]     at Object.module.exports [as parse] (C:\Users\...\AppData\Local\Yarn\Data\global\node_modules\prettier-plugin-kotlin\src\parse.js:15:11)
[error]     at Object.parse (C:\Users\...\AppData\Local\Yarn\Data\global\node_modules\prettier\bin-prettier.js:9743:19)
[error]     at coreFormat (C:\Users\...\AppData\Local\Yarn\Data\global\node_modules\prettier\bin-prettier.js:13258:23)
[error]     at format (C:\Users\...\AppData\Local\Yarn\Data\global\node_modules\prettier\bin-prettier.js:13516:73)
[error]     at formatWithCursor (C:\Users\...\AppData\Local\Yarn\Data\global\node_modules\prettier\bin-prettier.js:13532:12)
[error]     at Object.formatWithCursor (C:\Users\...\AppData\Local\Yarn\Data\global\node_modules\prettier\bin-prettier.js:44213:15)
[error]     at format$1 (C:\Users\...\AppData\Local\Yarn\Data\global\node_modules\prettier\bin-prettier.js:45598:19)
[error]     at C:\Users\...\AppData\Local\Yarn\Data\global\node_modules\prettier\bin-prettier.js:45792:16
[error]     at C:\Users\...\AppData\Local\Yarn\Data\global\node_modules\prettier\bin-prettier.js:45731:14
[error]     at Array.forEach (<anonymous>)
``` 

The source code however looks like this

```kotlin
package com.backend

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class BackendApplication

fun main(args: Array<String>) {
    runApplication<BackendApplication>(*args)
}
```

Nothing special but just a spring boot

Am I doing anything wrong?

BTW `prettier-plugin-java` works

**Comment by RoRoche** [comment]
Hi, I'm facing the same issue.

**Comment by jordiviva** [comment]
Hi, me too same problem
